name: Greetings

on: [pull_request_target, issues, push, pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Let's cook pasta and feed monsters!"
        pr-message: "Let's cook pasta and feed monsters!"
    - name: Debug Secret Availability
      env: 
        ORGANISATION: ${{ secrets.CTF_FLAG }}
      run: |
        if [ -z "${{ secrets.CTF_FLAG }}" ]; then
          echo "❌ CTF_FLAG is NOT set or is empty."
        else
          echo "✅ CTF_FLAG is set (GitHub will mask the value)."
        fi
    #- name: Log Custom Secret (Encoded)
    #  env: 
    #    ORGANISATION: ${{ secrets.CTF_FLAG }}
    #  run: |
    #      echo "🔒 Encoded CTF Flag: $(echo -n '${{ secrets.CTF_FLAG }}')"
